name: Verify PR
description: 'Verify PR with lint and test checks'
branding:
  color: purple
  icon: check-square
inputs:
  node-version:  # id of input
    description: 'Node Version'
    required: true
    default: '18'
  test-script:
    description: 'npm test script'
    required: true
    default: 'test:staged'
  with-coverage:
    description: 'Report test coverage'
    required: true
    default: 'true'
  github-token:
    description: 'github token'
    required: true
  run-lint:
    description: 'run lint checks'
    required: true
    default: 'true'
  run-commitlint:
    description: 'run commitlint'
    required: true
    default: 'true'
  run-tests:
    description: 'run tests'
    required: true
    default: 'true'
  test-all-files:
    description: 'run tests for all files'
    required: true
    default: 'false'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - uses: wagoid/commitlint-github-action@v5
      if: ${{ inputs.run-commitlint }} == 'true'

    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
        registry-url: 'https://npm.pkg.github.com'
        scope: 'refrens'

    - name: install dependencies
      run: npm ci
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ inputs.github-token }}

    - name: Run linters
      uses: wearerequired/lint-action@v2
      if: ${{ inputs.run-lint }} == 'true'
      with:
        github_token: ${{ inputs.github-token }}
        eslint: true
        prettier: true

    - name: Get changed files
      id: changed-files
      if: ${{ inputs.test-all-files }} == 'false' && ${{ inputs.run-tests == 'true' }}
      uses: tj-actions/changed-files@v43
      with:
        files: |
          **.ts
          **.tsx
          **.js
          **.jsx
          **.json
          **.mjs
          **.cjs

    - name: test changed files
      if: ${{ inputs.test-all-files }} == 'false' && ${{ inputs.run-tests == 'true' }} && steps.changed-files.outputs.any_changed == 'true'
      env:
        CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
      shell: bash
      run: |
        npm run ${{ inputs.test-script }} -- ${CHANGED_FILES}

    - name: test all files
      if: ${{ inputs.test-all-files }} != 'false' && ${{ inputs.run-tests == 'true' }}
      shell: bash
      run: |
        npm run ${{ inputs.test-script }}

    - name: Jest Coverage Comment
      if: ${{ inputs.with-coverage }} == 'true'
      uses: MishaKav/jest-coverage-comment@main
